#!/bin/bash
echo "**** YOUTUBE NEEDS CACHING .... PLEASE WAIT UNTIL THE CUBE SHOWS THE VIDEO"
echo "**** IF THE VIDEO IS NOT SHOWN AFTER ~15sec YOUR YOUTUBE-DL VERSION IS TOO OLD, NOT INSTALLED OR YOUTUBE-DL WAS NOT AVAILABLE WHEN MPV WAS COMPILED"
./mpvideocube ytdl://www.youtube.com/watch?v=zZct-itCwPE
